[package]
name = "chanman"
version = "0.1.0"
edition = "2021"

[dependencies]
tower-http = { "version" = "0.6.2", features = ["trace"] }
axum = "0.8.1"
serde = { version = "^1", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = ["full"] }
tower = "0.5.2"
